apiVersion: v1
kind: Secret
metadata:
  name: cms-secrets
  namespace: cms-prod
type: Opaque
stringData:
  db-password: "SuperSecretPassword123!"
  jwt-secret: "change-this-in-production-to-something-very-strong"
  db-host: "mysql-service.cms-prod.svc.cluster.local" # Can be secret if sensitive
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cms-config
  namespace: cms-prod
data:
  db-user: "root"
  db-name: "cms_db"
  db-port: "3306"
  node-env: "production"
  log-level: "info"
