apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cms-uploads-pvc
  namespace: cms-prod
spec:
  accessModes:
    - ReadWriteOnce # or ReadWriteMany if using NFS/EFS for scale-out
  resources:
    requests:
      storage: 5Gi
